/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\public\assets\Frigo.glb
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./assets/Frigo.glb");
  const { actions } = useAnimations(animations, group);
  console.log(actions);
  useEffect(() => {
    console.log(actions);
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name='Collada_visual_scene_group'
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name='model'>
              <group name='defaultMaterial' scale={0.02}>
                <mesh
                  name='defaultMaterial_1'
                  geometry={nodes.defaultMaterial_1.geometry}
                  material={materials.DefaultMaterial}
                />
                <mesh
                  name='defaultMaterial_2'
                  geometry={nodes.defaultMaterial_2.geometry}
                  material={materials.mat}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name='Plane008'
          position={[-3.11, 0.89, -0.06]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.45, 1, 0.89]}
        />
        <mesh
          name='Group#3_002'
          geometry={nodes["Group#3_002"].geometry}
          material={materials["Material.007"]}
          position={[7.35, 1.96, 0.28]}
          scale={[0.05, 0.06, 0.05]}
        />
        <group name='Group_009' position={[-0.84, 1.66, 0.6]} scale={0.06}>
          <mesh
            name='Mesh024'
            geometry={nodes.Mesh024.geometry}
            material={materials.Material8}
          />
          <mesh
            name='Mesh024_1'
            geometry={nodes.Mesh024_1.geometry}
            material={materials.Vitre}
          />
        </group>
        <group name='Group_010' position={[-0.84, 0.99, 0.6]} scale={0.06}>
          <mesh
            name='Mesh023'
            geometry={nodes.Mesh023.geometry}
            material={materials.Material8}
          />
          <mesh
            name='Mesh023_1'
            geometry={nodes.Mesh023_1.geometry}
            material={materials.Vitre}
          />
        </group>
        <group name='Group_011' position={[-0.84, 2.38, 0.6]} scale={0.06}>
          <mesh
            name='Mesh022'
            geometry={nodes.Mesh022.geometry}
            material={materials.Material8}
          />
          <mesh
            name='Mesh022_1'
            geometry={nodes.Mesh022_1.geometry}
            material={materials.Vitre}
          />
        </group>
        <group name='Group_012' position={[-0.84, 2.94, 0.6]} scale={0.06}>
          <mesh
            name='Mesh021'
            geometry={nodes.Mesh021.geometry}
            material={materials.Material8}
          />
          <mesh
            name='Mesh021_1'
            geometry={nodes.Mesh021_1.geometry}
            material={materials.Vitre}
          />
        </group>
        <group name='Group_013' position={[-0.84, 3.39, 0.42]} scale={0.06}>
          <mesh
            name='Mesh020'
            geometry={nodes.Mesh020.geometry}
            material={materials.Material8}
          />
          <mesh
            name='Mesh020_1'
            geometry={nodes.Mesh020_1.geometry}
            material={materials.Vitre}
          />
        </group>
        <mesh
          name='Group_026'
          geometry={nodes.Group_026.geometry}
          material={materials["Material.007"]}
          position={[7.34, 1.98, 0.33]}
          scale={[0.06, 0.12, 0.47]}
        />
        <group
          name='Text'
          position={[0.24, 3.12, 0.75]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name='Text002'
            geometry={nodes.Text002.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            name='Text002_1'
            geometry={nodes.Text002_1.geometry}
            material={materials.DefaultMaterial}
          />
        </group>
      </group>
    </group>
  );
}
export default Model;
useGLTF.preload("./assets/Frigo.glb");
